name: PR Branch Labeler

on: pull_request

jobs:
  label_prs:
    runs-on: ubuntu-latest
    steps:
    - name: Label PRs
      # if: github.event.action == 'opened'
      uses: chapulina/pr-branch-labeler@debugging
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
